FROM openjdk:8-alpine

WORKDIR /jpetstore

ADD src src
ADD pom.xml .

RUN	apk add maven | mvn -v
RUN mvn clean package

RUN wget http://mirror.navercorp.com/apache/tomcat/tomcat-7/v7.0.96/bin/apache-tomcat-7.0.96.tar.gz
RUN tar -zxf apache-tomcat-7.0.96.tar.gz
RUN cd apache-tomcat-7.0.96
RUN rm -rf webapps/ROOT
RUN cp /jpetstore/target/jpetstore.war webapps/ROOT.war
            
EXPOSE 8080
CMD ["/jpetstore/apache-tomcat-7.0.96/bin/catalina.sh", "run"]


