#CREATE DATABASE jpetstore;

USE jpetstore;

CREATE TABLE IF NOT EXISTS SUPPLIER (
   SUPPID INT NOT NULL, 
    NAME VARCHAR(80) NULL,
    STATUS VARCHAR(2) NOT NULL,
    ADDR1 VARCHAR(80) NULL,
    ADDR2 VARCHAR(80) NULL,
    CITY VARCHAR(80) NULL,
    STATE VARCHAR(80) NULL,
    ZIP VARCHAR(5) NULL,
    PHONE VARCHAR(80) NULL,  
PRIMARY KEY (SUPPID)) 
MIN_ROWS=0 
MAX_ROWS=1000 
PACK_KEYS=DEFAULT 
ROW_FORMAT=DEFAULT 
COMMENT='CADASTRO DE FORNECEDORES';

CREATE TABLE IF NOT EXISTS SIGNON (
    USERNAME VARCHAR(25) NOT NULL,
    PASSWORD VARCHAR(25)  NOT NULL,  
PRIMARY KEY (USERNAME)) 
MIN_ROWS=0 
MAX_ROWS=1000  
PACK_KEYS=DEFAULT 
ROW_FORMAT=DEFAULT 
COMMENT='CADASTRO DE USUáRIOS';

CREATE TABLE IF NOT EXISTS ACCOUNT (
    USERID VARCHAR(80) NOT NULL,
    EMAIL VARCHAR(80) NOT NULL,
    FIRSTNAME VARCHAR(80) NOT NULL,
    LASTNAME VARCHAR(80) NOT NULL,
    STATUS VARCHAR(2)  NULL,
    ADDR1 VARCHAR(80) NOT NULL,
    ADDR2 VARCHAR(40) NULL,
    CITY VARCHAR(80) NOT  NULL,
    STATE VARCHAR(80) NOT NULL,
    ZIP VARCHAR(20) NOT NULL,
    COUNTRY VARCHAR(20) NOT NULL,
    PHONE VARCHAR(80) NOT NULL,
PRIMARY KEY (USERID) )
MIN_ROWS=0 
MAX_ROWS=1000  
PACK_KEYS=DEFAULT 
ROW_FORMAT=DEFAULT 
COMMENT='CADASTRO DE CONTAS';

CREATE TABLE IF NOT EXISTS PROFILE (
    USERID VARCHAR(80) NOT NULL,
    LANGPREF VARCHAR(80) NOT NULL,
    FAVCATEGORY VARCHAR(30),
    MYLISTOPT BOOL,
    BANNEROPT BOOL,
PRIMARY KEY (USERID) )
PACK_KEYS=DEFAULT 
ROW_FORMAT=DEFAULT 
COMMENT='CADASTRO DE PERFIS';

CREATE TABLE IF NOT EXISTS BANNERDATA (
    FAVCATEGORY VARCHAR(80) NOT NULL,
    BANNERNAME VARCHAR(255)  NULL, 
PRIMARY KEY (FAVCATEGORY))
PACK_KEYS=DEFAULT 
ROW_FORMAT=DEFAULT 
COMMENT='BANNER DATA';

CREATE TABLE IF NOT EXISTS ORDERS (
      ORDERID INT NOT NULL,
      USERID VARCHAR(80) NOT NULL,
      ORDERDATE DATE NOT NULL,
      SHIPADDR1 VARCHAR(80) NOT NULL,
      SHIPADDR2 VARCHAR(80) NULL,
      SHIPCITY VARCHAR(80) NOT NULL,
      SHIPSTATE VARCHAR(80) NOT NULL,
      SHIPZIP VARCHAR(20) NOT NULL,
      SHIPCOUNTRY VARCHAR(20) NOT NULL,
      BILLADDR1 VARCHAR(80) NOT NULL,
      BILLADDR2 VARCHAR(80)  NULL,
      BILLCITY VARCHAR(80) NOT NULL,
      BILLSTATE VARCHAR(80) NOT NULL,
      BILLZIP VARCHAR(20) NOT NULL,
      BILLCOUNTRY VARCHAR(20) NOT NULL,
      COURIER VARCHAR(80) NOT NULL,
      TOTALPRICE DECIMAL(10,2) NOT NULL,
      BILLTOFIRSTNAME VARCHAR(80) NOT NULL,
      BILLTOLASTNAME VARCHAR(80) NOT NULL,
      SHIPTOFIRSTNAME VARCHAR(80) NOT NULL,
      SHIPTOLASTNAME VARCHAR(80) NOT NULL,
      CREDITCARD VARCHAR(80) NOT NULL,
      EXPRDATE VARCHAR(7) NOT NULL,
      CARDTYPE VARCHAR(80) NOT NULL,
      LOCALE VARCHAR(80) NOT NULL,
PRIMARY KEY (ORDERID) )
PACK_KEYS=DEFAULT 
ROW_FORMAT=DEFAULT 
COMMENT='CADASTRO DE PEDIDOS';

CREATE TABLE IF NOT EXISTS ORDERSTATUS (
      ORDERID INT NOT NULL,
      LINENUM INT NOT NULL,
      TIMESTAMP DATE NOT NULL,
      STATUS VARCHAR(2) NOT NULL,
PRIMARY KEY (ORDERID, LINENUM) )
PACK_KEYS=DEFAULT 
ROW_FORMAT=DEFAULT 
COMMENT='STATUS DE PEDIDOS';

CREATE TABLE IF NOT EXISTS LINEITEM (
      ORDERID INT NOT NULL,
      LINENUM INT NOT NULL,
      ITEMID VARCHAR(10) NOT NULL,
      QUANTITY INT NOT NULL,
      UNITPRICE DECIMAL(10,2) NOT NULL,
PRIMARY KEY (ORDERID, LINENUM) )
PACK_KEYS=DEFAULT 
ROW_FORMAT=DEFAULT 
COMMENT='LINE ITEM';

CREATE TABLE IF NOT EXISTS CATEGORY (
	CATID VARCHAR(10) NOT NULL,
	NAME VARCHAR(80) NULL,
	DESCN VARCHAR(255) NULL,
PRIMARY KEY (CATID) )
PACK_KEYS=DEFAULT 
ROW_FORMAT=DEFAULT 
COMMENT='CATEGORIAS';

CREATE TABLE IF NOT EXISTS PRODUCT (
    PRODUCTID VARCHAR(10) NOT NULL,
    CATEGORY VARCHAR(10) NOT NULL,
    NAME VARCHAR(80) NULL,
    DESCN VARCHAR(255) NULL,
PRIMARY KEY (PRODUCTID) )
PACK_KEYS=DEFAULT 
ROW_FORMAT=DEFAULT 
COMMENT='CATEGORIAS';

ALTER TABLE PRODUCT 
	ADD INDEX PRODUCTCAT(CATEGORY);

ALTER TABLE PRODUCT 
	ADD INDEX PRODUCTNAME(NAME);

ALTER TABLE CATEGORY 
	ADD INDEX IXCATEGORYPRODUCT(CATID);

ALTER TABLE PRODUCT  ADD FOREIGN KEY (CATEGORY) 
         REFERENCES CATEGORY(CATID) 
         ON DELETE RESTRICT 
         ON UPDATE RESTRICT;

CREATE TABLE IF NOT EXISTS ITEM (
    ITEMID VARCHAR(10) NOT NULL,
    PRODUCTID VARCHAR(10) NOT NULL,
    LISTPRICE DECIMAL(10,2) NULL,
    UNITCOST DECIMAL(10,2) NULL,
    SUPPLIER INT NULL,
    STATUS VARCHAR(2) NULL,
    ATTR1 VARCHAR(80) NULL,
    ATTR2 VARCHAR(80) NULL,
    ATTR3 VARCHAR(80) NULL,
    ATTR4 VARCHAR(80) NULL,
    ATTR5 VARCHAR(80) NULL,
PRIMARY KEY (ITEMID) )
PACK_KEYS=DEFAULT 
ROW_FORMAT=DEFAULT 
COMMENT='ITENS';

ALTER TABLE ITEM 
	ADD INDEX ITEMPROD(PRODUCTID);

ALTER TABLE ITEM ADD FOREIGN KEY (PRODUCTID) 
         REFERENCES PRODUCT(PRODUCTID) 
         ON DELETE RESTRICT 
         ON UPDATE RESTRICT;

ALTER TABLE ITEM ADD FOREIGN KEY (SUPPLIER) 
         REFERENCES SUPPLIER(SUPPID) 
         ON DELETE RESTRICT 
         ON UPDATE RESTRICT;

CREATE TABLE IF NOT EXISTS INVENTORY (
    ITEMID VARCHAR(10) NOT NULL,
    QTY INT NOT NULL,
PRIMARY KEY (ITEMID) )
PACK_KEYS=DEFAULT 
ROW_FORMAT=DEFAULT 
COMMENT='INVENTORY';

CREATE TABLE IF NOT EXISTS SEQUENCE (
    NAME               VARCHAR(30)  NOT NULL,
    NEXTID             INT          NOT NULL,
PRIMARY KEY (NAME) )
PACK_KEYS=DEFAULT 
ROW_FORMAT=DEFAULT 
COMMENT='INVENTORY';
